In [108]:
import numpy as np

In [109]:
#We create a 4 x 3 array with binary entries
inputs = np.array([[0,0,1],
                   [1,1,1],
                   [1,0,1],
                   [0,1,1]])

In [110]:
inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [111]:
#This is our output variable, also binary, and 4x1
outputs = np.array([[0,1,1,0]]).T

In [112]:
#here, we define our sigmoid function, which we will use to adjust our weights, sigmoid_der is the partial derivative
# of the sigmoid equation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_der(x):
    return x * (1-x)

In [113]:
np.random.seed(1)
#This establishs random weights for each input. 
weights = 2 * np.random.random((3,1)) - 1

In [114]:
weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [115]:
print('random starting synaptic weights are:')
print(weights)

random starting synaptic weights are:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [116]:
#This is where our neural network learns...
#our prediction is using the sigmoid equation and multiplying the input layer by the random weights
# once completed, we calculate the adjusted error, then we make adjustments by figuring out the partial derivative of our predictions
# We update our weights, and then start again, until we get optimal weights for our neural network
for iteration in range(20000):
    
    inlayer = inputs
    pred_out = sigmoid(np.dot(inputs,weights))
    
    error = outputs - pred_out
    
    adj = error * sigmoid_der(pred_out)
    
    weights += np.dot(inlayer.T,adj)
    

In [118]:
print('synaptic Weights:')
print(weights)
print("Here are the outputs:")
print(out)

synaptic Weights:
[[ 10.38040701]
 [ -0.20641179]
 [ -4.98452047]]
Here are the outputs:
[[ 0.2689864 ]
 [ 0.3262757 ]
 [ 0.23762817]
 [ 0.36375058]]
